title: CmdrNorthpaw's blog
author: CmdrNorthpaw
email: thetuxkid@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Hi! I'm CmdrNorthpaw. I dabble in Java, Kotlin, Python and Linux. Here is my blog,
  and if I've set this up right there should be some links up above to social media
  and some stuff that I've made. 
show_excerpts: true # set to true to show excerpts on the homepage

paginate: 10
paginate_path: "/blog/page:num/"

permalink: /:category/:title

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: bitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://bitbrain.itch.io
      icon: reddit
      color: red
    - url: https://github.com/CmdrNorthpaw
      icon: github-circle
      color: purple

  show_author: true

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging

# Replaces the default avatar provider (gravatar)
#avatar_source: github
#github_username: bitbrain
